sonar.projectKey=Berkilic41_ecommerce-api
sonar.organization=berkilic41
sonar.projectName=Mini E-Commerce REST API
sonar.projectVersion=1.0

sonar.sources=ECommerceAPI
sonar.tests=tests
sonar.exclusions=**/Migrations/**,**/obj/**,**/bin/**

sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/test-results.trx
